services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: hotelhub
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    container_name: springboot
    build:
      context: ./SDP-Backend
      dockerfile: C:\Users\PUNEETH\Desktop\New SDP Project\SDP - Project\SDP-FULLSTACK\backend.Dockerfile
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    container_name: react
    build:
      context: ./SDP-Frontend
      dockerfile: C:\Users\PUNEETH\Desktop\New SDP Project\SDP - Project\SDP-FULLSTACK\frontend.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

# Declare volumes
volumes:
  mysql-data: