services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: hotelhub
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - springboot-react-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    container_name: springboot
    build:
      context: ./SDP-Backend
      dockerfile: ../SDP-FULLSTACK/backend.Dockerfile   # relative to context
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure
    networks:
      - springboot-react-network

  frontend:
    container_name: react
    build:
      context: .                                       # <— project root as context
      dockerfile: ./SDP-FULLSTACK/frontend.Dockerfile  # path from root to Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - springboot-react-network

volumes:
  mysql-data:

networks:
  springboot-react-network:
    driver: bridge